/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author 1matt
 */
import java.awt.Toolkit;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.table.DefaultTableModel;

public class JHome extends javax.swing.JFrame {

    /**
     * Creates new form JHome
     */
    public JHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane1 = new javax.swing.JScrollPane();
        textbox = new javax.swing.JTextArea();
        label = new javax.swing.JLabel();
        scrollpane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        combobox = new javax.swing.JComboBox<>();
        togglebutton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        progbar = new javax.swing.JProgressBar();
        targetCombo = new javax.swing.JComboBox<>();
        targetGoal = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        category1 = new javax.swing.JMenu();
        category2 = new javax.swing.JMenu();
        c2_clear = new javax.swing.JMenuItem();
        c2_separator1 = new javax.swing.JPopupMenu.Separator();
        c2_copyText = new javax.swing.JMenuItem();
        c2_copyInfo = new javax.swing.JMenuItem();
        category3 = new javax.swing.JMenu();
        c3_doc = new javax.swing.JMenuItem();
        c3_con = new javax.swing.JMenuItem();
        c3_separator1 = new javax.swing.JPopupMenu.Separator();
        c3_bug = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WordCounter (pre-release)");

        textbox.setColumns(20);
        textbox.setLineWrap(true);
        textbox.setRows(5);
        textbox.setTabSize(4);
        textbox.setWrapStyleWord(true);
        textbox.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textboxCaretUpdate(evt);
            }
        });
        scrollpane1.setViewportView(textbox);

        label.setText("Information");

        scrollpane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Value"
            }
        ));
        jTable3.setToolTipText("WordCounter (1.0)");
        jTable3.setAutoscrolls(false);
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable3.setIntercellSpacing(new java.awt.Dimension(4, 4));
        jTable3.setMaximumSize(new java.awt.Dimension(30, 440));
        jTable3.setRowHeight(22);
        jTable3.setShowGrid(true);
        jTable3.setShowHorizontalLines(false);
        jTable3.setShowVerticalLines(false);
        scrollpane2.setViewportView(jTable3);

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View: General", "View: Advanced (A-Z)", "View: Advanced (Extras)" }));
        combobox.setEnabled(false);

        togglebutton.setText("Toggle always on top");
        togglebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                togglebuttonMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));

        progbar.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        progbar.setForeground(new java.awt.Color(0, 120, 215));
        progbar.setValue(80);
        progbar.setPreferredSize(new java.awt.Dimension(146, 15));
        progbar.setStringPainted(true);

        targetCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Words" }));
        targetCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetComboActionPerformed(evt);
            }
        });

        targetGoal.setModel(new javax.swing.SpinnerNumberModel(200, 0, 10000, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(targetCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(targetGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(progbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Targets (optional)");

        category1.setText("Settings");
        category1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                category1MouseClicked(evt);
            }
        });
        menubar.add(category1);

        category2.setText("Tools");

        c2_clear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        c2_clear.setText("Clear");
        c2_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2_clearActionPerformed(evt);
            }
        });
        category2.add(c2_clear);
        category2.add(c2_separator1);

        c2_copyText.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        c2_copyText.setText("(copy) Textbox");
        c2_copyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2_copyTextActionPerformed(evt);
            }
        });
        category2.add(c2_copyText);

        c2_copyInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        c2_copyInfo.setText("(copy) Infolog");
        c2_copyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2_copyInfoActionPerformed(evt);
            }
        });
        category2.add(c2_copyInfo);

        menubar.add(category2);

        category3.setText("Help");

        c3_doc.setText("Documentation");
        c3_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3_docActionPerformed(evt);
            }
        });
        category3.add(c3_doc);

        c3_con.setText("Contribute");
        c3_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3_conActionPerformed(evt);
            }
        });
        category3.add(c3_con);
        category3.add(c3_separator1);

        c3_bug.setText("Create bug report");
        c3_bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3_bugActionPerformed(evt);
            }
        });
        category3.add(c3_bug);

        menubar.add(category3);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollpane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(combobox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 262, Short.MAX_VALUE)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(togglebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(togglebutton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textboxCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textboxCaretUpdate
        DefaultTableModel jGrid = Interpret.updateTable(textbox.getText(), false);
        jTable3.setModel(jGrid);
        progbar.setMaximum((int) targetGoal.getValue()); int a = 0; int b = 0; int c = 0;
        progbar.setValue(Interpret.getWords(textbox.getText()));
    }//GEN-LAST:event_textboxCaretUpdate

    private void togglebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_togglebuttonMouseClicked
        setAlwaysOnTop(!isAlwaysOnTop());
    }//GEN-LAST:event_togglebuttonMouseClicked

    private void category1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_category1MouseClicked
        JSettings.main(null);
    }//GEN-LAST:event_category1MouseClicked

    private void c3_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3_docActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://github.com/ST10257002/MP-WordCounter/wiki"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_c3_docActionPerformed

    private void c3_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3_conActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://github.com/ST10257002/MP-WordCounter/blob/main/CONTRIBUTE.md"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_c3_conActionPerformed

    private void c3_bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3_bugActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://github.com/ST10257002/MP-WordCounter/issues"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_c3_bugActionPerformed

    private void c2_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2_clearActionPerformed
        textbox.setText("");
    }//GEN-LAST:event_c2_clearActionPerformed

    private void c2_copyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2_copyTextActionPerformed
        Toolkit.getDefaultToolkit()
                .getSystemClipboard()
                .setContents(
                        new java.awt.datatransfer.StringSelection(textbox.getText()),
                        null
                );
    }//GEN-LAST:event_c2_copyTextActionPerformed

    private void c2_copyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2_copyInfoActionPerformed
        Toolkit.getDefaultToolkit()
                .getSystemClipboard()
                .setContents(
                        new java.awt.datatransfer.StringSelection(Interpret.updateLogFile(textbox.getText())),
                        null
                );
    }//GEN-LAST:event_c2_copyInfoActionPerformed

    private void targetComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem c2_clear;
    private javax.swing.JMenuItem c2_copyInfo;
    private javax.swing.JMenuItem c2_copyText;
    private javax.swing.JPopupMenu.Separator c2_separator1;
    private javax.swing.JMenuItem c3_bug;
    private javax.swing.JMenuItem c3_con;
    private javax.swing.JMenuItem c3_doc;
    private javax.swing.JPopupMenu.Separator c3_separator1;
    public javax.swing.JMenu category1;
    private javax.swing.JMenu category2;
    public javax.swing.JMenu category3;
    public javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTable jTable3;
    public javax.swing.JLabel label;
    public javax.swing.JMenuBar menubar;
    public javax.swing.JProgressBar progbar;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JScrollPane scrollpane2;
    private javax.swing.JComboBox<String> targetCombo;
    private javax.swing.JSpinner targetGoal;
    public javax.swing.JTextArea textbox;
    private javax.swing.JToggleButton togglebutton;
    // End of variables declaration//GEN-END:variables
}
